name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t product-container .

      - name: Stop old container
        run: |
          docker stop product-container || true
          docker rm product-container || true

      - name: Run new container
        run: docker run -d -p 8081:80 --name product-container product-container
